# Generated by Django 5.1.6 on 2025-05-15 10:29

import apps.mapping.models
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(db_index=True, max_length=30, null=True)),
                ('result', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MappingSessionUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(db_index=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MappingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(db_index=True, max_length=30, null=True)),
                ('app_version', models.CharField(max_length=10)),
                ('client_type', django_choices_field.fields.IntegerChoicesField(choices=[(0, 'Unknown'), (1, 'Mobile (Android)'), (2, 'Mobile (IOS)'), (3, 'Web')], choices_enum=apps.mapping.models.MappingSessionClientTypeEnum)),
                ('items_count', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('contributor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contributor.contributoruser')),
            ],
        ),
    ]
