# Generated by Django 5.2.5 on 2025-09-10 17:23

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MappingSessionResultTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_firebase_id', models.CharField(max_length=255)),
                ('group_firebase_id', models.CharField(max_length=255)),
                ('contributor_user_firebase_id', models.CharField(max_length=255)),
                ('task_firebase_id', models.CharField(max_length=255)),
                ('group_id', models.BigIntegerField(blank=True, null=True)),
                ('task_id', models.BigIntegerField(blank=True, null=True)),
                ('contributor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('result', models.PositiveSmallIntegerField()),
                ('app_version', models.CharField(max_length=255)),
                ('client_type', django_choices_field.fields.IntegerChoicesField(choices=[(0, 'Unknown'), (1, 'Mobile (Android)'), (2, 'Mobile (IOS)'), (3, 'Web')])),
                ('is_firebase_mapping_valid', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MappingSessionUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MappingSessionUserGroupTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_firebase_id', models.CharField(max_length=255)),
                ('group_firebase_id', models.CharField(max_length=255)),
                ('contributor_user_firebase_id', models.CharField(max_length=255)),
                ('user_group_firebase_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MappingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(max_length=10)),
                ('client_type', django_choices_field.fields.IntegerChoicesField(choices=[(0, 'Unknown'), (1, 'Mobile (Android)'), (2, 'Mobile (IOS)'), (3, 'Web')])),
                ('items_count', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('contributor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contributor.contributoruser')),
            ],
        ),
    ]
