# Generated by Django 5.1.6 on 2025-04-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapping', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsession',
            name='project_task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.projecttaskgroup'),
        ),
        migrations.AddField(
            model_name='mappingsessionresult',
            name='project_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.projecttask'),
        ),
        migrations.AddField(
            model_name='mappingsessionresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.mappingsession'),
        ),
    ]
