# Generated by Django 5.2.5 on 2025-09-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributor', '0001_initial'),
        ('mapping', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsession',
            name='project_task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.projecttaskgroup'),
        ),
        migrations.AddField(
            model_name='mappingsessionresult',
            name='project_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.projecttask'),
        ),
        migrations.AddField(
            model_name='mappingsessionresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.mappingsession'),
        ),
        migrations.AddField(
            model_name='mappingsessionusergroup',
            name='mapping_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.mappingsession'),
        ),
        migrations.AddField(
            model_name='mappingsessionusergroup',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contributor.contributorusergroup'),
        ),
        migrations.AlterUniqueTogether(
            name='mappingsession',
            unique_together={('project_task_group', 'contributor_user')},
        ),
        migrations.AlterUniqueTogether(
            name='mappingsessionresult',
            unique_together={('session', 'project_task')},
        ),
        migrations.AlterUniqueTogether(
            name='mappingsessionusergroup',
            unique_together={('mapping_session', 'user_group')},
        ),
    ]
