# Generated by Django 5.1.6 on 2025-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsession',
            name='old_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mappingsessionresult',
            name='old_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
    ]
