# Generated by Django 5.2.5 on 2025-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingsession',
            name='app_version',
            field=models.CharField(max_length=255),
        ),
    ]
