# Generated by Django 5.1.6 on 2025-08-01 06:05

import django.db.models.manager
from django.db import migrations, models
from ulid import ULID


def set_firebase_id_for_mapping_session(apps, schema_editor):
    Model = apps.get_model('mapping', 'MappingSession')
    for obj in Model.cte_objects.all():
        obj.firebase_id = str(ULID())
        obj.save(update_fields=['firebase_id'])

def set_firebase_id_for_mapping_session_result(apps, schema_editor):
    Model = apps.get_model('mapping', 'MappingSessionResult')
    for obj in Model.cte_objects.all():
        obj.firebase_id = str(ULID())
        obj.save(update_fields=['firebase_id'])

def set_firebase_id_for_mapping_session_user_group(apps, schema_editor):
    Model = apps.get_model('mapping', 'MappingSessionUserGroup')
    for obj in Model.cte_objects.all():
        obj.firebase_id = str(ULID())
        obj.save(update_fields=['firebase_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mappingsession',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mappingsessionresult',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mappingsessionusergroup',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='mappingsession',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='mappingsessionresult',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='mappingsessionusergroup',
            name='old_id',
        ),
        migrations.AddField(
            model_name='mappingsession',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mappingsession',
            name='firebase_last_pulled',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pulled from firebase', null=True),
        ),
        migrations.AddField(
            model_name='mappingsessionresult',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mappingsessionresult',
            name='firebase_last_pulled',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pulled from firebase', null=True),
        ),
        migrations.AddField(
            model_name='mappingsessionusergroup',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mappingsessionusergroup',
            name='firebase_last_pulled',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pulled from firebase', null=True),
        ),
        migrations.RunPython(set_firebase_id_for_mapping_session, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_firebase_id_for_mapping_session_result, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_firebase_id_for_mapping_session_user_group, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mappingsession',
            name='firebase_id',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mappingsessionresult',
            name='firebase_id',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mappingsessionusergroup',
            name='firebase_id',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
