# Generated by Django 5.2.4 on 2025-08-06 09:54

import apps.mapping.models
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_alter_mappingsession_managers_and_more'),
        ('project', '0016_rename_stats_type_projectasset_export_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSessionResultTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_firebase_id', models.CharField(max_length=255)),
                ('group_firebase_id', models.CharField(max_length=255)),
                ('contributor_user_firebase_id', models.CharField(max_length=255)),
                ('task_firebase_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('result', models.PositiveSmallIntegerField()),
                ('app_version', models.CharField(max_length=255)),
                ('client_type', django_choices_field.fields.IntegerChoicesField(choices=[(0, 'Unknown'), (1, 'Mobile (Android)'), (2, 'Mobile (IOS)'), (3, 'Web')], choices_enum=apps.mapping.models.MappingSessionClientTypeEnum)),
            ],
        ),
        migrations.CreateModel(
            name='MappingSessionUserGroupTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_firebase_id', models.CharField(max_length=255)),
                ('group_firebase_id', models.CharField(max_length=255)),
                ('contributor_user_firebase_id', models.CharField(max_length=255)),
                ('user_group_firebase_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelManagers(
            name='mappingsession',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='mappingsessionresult',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='mappingsessionusergroup',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='mappingsession',
            name='firebase_id',
        ),
        migrations.RemoveField(
            model_name='mappingsession',
            name='firebase_last_pulled',
        ),
        migrations.AlterUniqueTogether(
            name='mappingsessionresult',
            unique_together={('session', 'project_task')},
        ),
        migrations.RemoveField(
            model_name='mappingsessionusergroup',
            name='firebase_id',
        ),
        migrations.RemoveField(
            model_name='mappingsessionusergroup',
            name='firebase_last_pulled',
        ),
        migrations.RemoveField(
            model_name='mappingsessionresult',
            name='firebase_id',
        ),
        migrations.RemoveField(
            model_name='mappingsessionresult',
            name='firebase_last_pulled',
        ),
    ]
