# Generated by Django 5.1.6 on 2025-05-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0006_alter_contributorusergroup_managers_and_more'),
        ('mapping', '0003_mappingsession_old_id_mappingsessionresult_old_id'),
        ('project', '0012_alter_organization_managers_alter_project_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mappingsession',
            unique_together={('project_task_group', 'contributor_user')},
        ),
        migrations.CreateModel(
            name='MappingSessionUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(db_index=True, max_length=30, null=True)),
                ('mapping_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.mappingsession')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contributor.contributorusergroup')),
            ],
            options={
                'unique_together': {('mapping_session', 'user_group')},
            },
        ),
    ]
