# Generated by Django 5.2.5 on 2025-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_alter_mappingsession_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsessionresult',
            name='reference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappingsessionresulttemp',
            name='reference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
