# Generated by Django 5.2.5 on 2026-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_alter_mappingsession_app_version'),
        ('project', '0011_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mappingsessionresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mappingsessionresult',
            name='task_partition_index',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mappingsessionresulttemp',
            name='task_partition_index',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mappingsessionresult',
            unique_together={('session', 'project_task', 'task_partition_index')},
        ),
    ]
