# Generated by Django 5.2.4 on 2025-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_mappingsessionresulttemp_mappingsessionusergrouptemp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsessionresulttemp',
            name='contributor_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappingsessionresulttemp',
            name='group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappingsessionresulttemp',
            name='is_firebase_mapping_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappingsessionresulttemp',
            name='task_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
