# Generated by Django 5.2.5 on 2025-09-10 17:23

import apps.tutorial.models
import django.core.files.storage
import django.db.models.manager
import django_choices_field.fields
import main.fields
import utils.common
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('name', models.CharField(max_length=255)),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Draft'), (15, 'Ready to Publish'), (16, 'Publishing Failed'), (40, 'Discarded'), (20, 'Published'), (30, 'Archived')], default=10)),
                ('status_message', models.CharField(blank=True, max_length=510, null=True)),
                ('firebase_id', models.CharField(default=apps.tutorial.models.generate_tutorial_firebase_id, max_length=40, unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', django_choices_field.fields.IntegerChoicesField(choices=[(100, 'Input'), (200, 'Output'), (300, 'Export'), (400, 'Debug')])),
                ('mimetype', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'application/geo+json'), (101, 'application/json'), (201, 'image/jpeg'), (202, 'image/png'), (203, 'image/gif'), (300, 'application/x-gzip'), (400, 'text/csv'), (500, 'text/plain')], null=True)),
                ('file_size', models.PositiveIntegerField(help_text='The size of the file in bytes')),
                ('marked_as_deleted', models.BooleanField(default=False, help_text='If this flag is enabled, this asset will be deleted in the future')),
                ('external_url', models.CharField(blank=True, help_text='Provide link to the file associated with the asset', null=True)),
                ('input_type', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'Image for information block')], null=True)),
                ('file', main.fields.OverwritableFileField(help_text='The file associated with the asset', max_length=255, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=apps.tutorial.models.UploadHelper.tutorial_asset)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialInformationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('page_number', models.PositiveSmallIntegerField()),
            ],
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialInformationPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('block_number', models.PositiveSmallIntegerField()),
                ('block_type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Text'), (2, 'Image')])),
                ('text', models.TextField(blank=True, null=True)),
            ],
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialScenarioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('scenario_page_number', models.PositiveSmallIntegerField()),
                ('instructions_description', models.CharField(max_length=255)),
                ('instructions_icon', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'add-outline'), (2, 'alert-outline'), (3, 'ban-outline'), (4, 'check'), (5, 'close-outline'), (33, 'checkmark-outline'), (6, 'egg-outline'), (7, 'ellipse-outline'), (8, 'flag-outline'), (9, 'hand-left-outline'), (10, 'hand-right-outline'), (11, 'happy-outline'), (12, 'heart-outline'), (13, 'help-outline'), (14, 'information-outline'), (15, 'prism-outline'), (16, 'refresh-outline'), (17, 'remove-outline'), (18, 'sad-outline'), (19, 'search-outline'), (20, 'shapes-outline'), (21, 'square-outline'), (22, 'star-outline'), (23, 'thumbs-down-outline'), (24, 'thumbs-up-outline'), (25, 'triangle-outline'), (26, 'warning-outline'), (27, 'general-tap'), (28, 'tap'), (29, 'tap-1'), (30, 'tap-2'), (31, 'tap-3'), (32, 'swipe-left')])),
                ('instructions_title', models.CharField(max_length=255)),
                ('hint_description', models.CharField(max_length=255)),
                ('hint_icon', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'add-outline'), (2, 'alert-outline'), (3, 'ban-outline'), (4, 'check'), (5, 'close-outline'), (33, 'checkmark-outline'), (6, 'egg-outline'), (7, 'ellipse-outline'), (8, 'flag-outline'), (9, 'hand-left-outline'), (10, 'hand-right-outline'), (11, 'happy-outline'), (12, 'heart-outline'), (13, 'help-outline'), (14, 'information-outline'), (15, 'prism-outline'), (16, 'refresh-outline'), (17, 'remove-outline'), (18, 'sad-outline'), (19, 'search-outline'), (20, 'shapes-outline'), (21, 'square-outline'), (22, 'star-outline'), (23, 'thumbs-down-outline'), (24, 'thumbs-up-outline'), (25, 'triangle-outline'), (26, 'warning-outline'), (27, 'general-tap'), (28, 'tap'), (29, 'tap-1'), (30, 'tap-2'), (31, 'tap-3'), (32, 'swipe-left')])),
                ('hint_title', models.CharField(max_length=255)),
                ('success_description', models.CharField(max_length=255)),
                ('success_icon', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'add-outline'), (2, 'alert-outline'), (3, 'ban-outline'), (4, 'check'), (5, 'close-outline'), (33, 'checkmark-outline'), (6, 'egg-outline'), (7, 'ellipse-outline'), (8, 'flag-outline'), (9, 'hand-left-outline'), (10, 'hand-right-outline'), (11, 'happy-outline'), (12, 'heart-outline'), (13, 'help-outline'), (14, 'information-outline'), (15, 'prism-outline'), (16, 'refresh-outline'), (17, 'remove-outline'), (18, 'sad-outline'), (19, 'search-outline'), (20, 'shapes-outline'), (21, 'square-outline'), (22, 'star-outline'), (23, 'thumbs-down-outline'), (24, 'thumbs-up-outline'), (25, 'triangle-outline'), (26, 'warning-outline'), (27, 'general-tap'), (28, 'tap'), (29, 'tap-1'), (30, 'tap-2'), (31, 'tap-3'), (32, 'swipe-left')])),
                ('success_title', models.CharField(max_length=255)),
            ],
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reference', models.PositiveSmallIntegerField()),
                ('project_type_specifics', models.JSONField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
