# Generated by Django 5.1.6 on 2025-03-06 09:50

import apps.tutorial.models
import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True, help_text='Draft tutorial can be modified')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this tutorial is referring to.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='project.project')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialInformationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tutorial.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialInformationPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveSmallIntegerField()),
                ('block_type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Text'), (2, 'Image')], choices_enum=apps.tutorial.models.TutorialInformationPageBlockType)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.tutorial.models.UploadHelper.information_page_block_image)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tutorial.tutorialinformationpage')),
            ],
        ),
    ]
