# Generated by Django 5.1.6 on 2025-04-01 16:30

import apps.tutorial.models
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True, help_text='Draft tutorial can be modified')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialInformationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialInformationPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveSmallIntegerField()),
                ('block_type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Text'), (2, 'Image')], choices_enum=apps.tutorial.models.TutorialInformationPageBlockTypeEnum)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.tutorial.models.UploadHelper.information_page_block_image)),
            ],
        ),
    ]
