# Generated by Django 5.1.6 on 2025-05-16 08:29

import apps.common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tutorialscenariopage',
            name='unique_scenario_on_tutorials',
        ),
        migrations.RenameField(
            model_name='tutorialscenariopage',
            old_name='scenario_id',
            new_name='scenario_page_number',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='client_id',
            field=models.CharField(max_length=26, unique=True, validators=[apps.common.models.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='tutorialinformationpage',
            name='client_id',
            field=models.CharField(max_length=26, unique=True, validators=[apps.common.models.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='tutorialinformationpageblock',
            name='client_id',
            field=models.CharField(max_length=26, unique=True, validators=[apps.common.models.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='tutorialscenariopage',
            name='client_id',
            field=models.CharField(max_length=26, unique=True, validators=[apps.common.models.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='tutorialtask',
            name='client_id',
            field=models.CharField(max_length=26, unique=True, validators=[apps.common.models.validate_ulid]),
        ),
        migrations.AddConstraint(
            model_name='tutorialscenariopage',
            constraint=models.UniqueConstraint(fields=('tutorial', 'scenario_page_number'), name='unique_scenario_on_tutorials'),
        ),
    ]
