# Generated by Django 5.2.5 on 2026-02-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialtask',
            name='task_partition_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
