# Generated by Django 5.1.6 on 2025-05-12 11:02

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tutorial',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
