# Generated by Django 5.1.6 on 2025-05-07 05:11

import apps.tutorial.models
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialScenarioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('scenario_id', models.PositiveSmallIntegerField()),
                ('instructions_description', models.CharField(max_length=255)),
                ('instructions_icon', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'add-outline'), (2, 'alert-outline'), (3, 'ban-outline'), (4, 'check'), (5, 'close-outline'), (33, 'checkmark-outline'), (6, 'egg-outline'), (7, 'ellipse-outline'), (8, 'flag-outline'), (9, 'hand-left-outline'), (10, 'hand-right-outline'), (11, 'happy-outline'), (12, 'heart-outline'), (13, 'help-outline'), (14, 'information-outline'), (15, 'prism-outline'), (16, 'refresh-outline'), (17, 'remove-outline'), (18, 'sad-outline'), (19, 'search-outline'), (20, 'shapes-outline'), (21, 'square-outline'), (22, 'star-outline'), (23, 'thumbs-down-outline'), (24, 'thumbs-up-outline'), (25, 'triangle-outline'), (26, 'warning-outline'), (27, 'general-tap'), (28, 'tap'), (29, 'tap-1'), (30, 'tap-2'), (31, 'tap-3'), (32, 'swipe-left')], choices_enum=apps.tutorial.models.TutorialScenarioIconEnum)),
                ('instructions_title', models.CharField(max_length=255)),
                ('hint_description', models.CharField(blank=True, max_length=255, null=True)),
                ('hint_icon', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'add-outline'), (2, 'alert-outline'), (3, 'ban-outline'), (4, 'check'), (5, 'close-outline'), (33, 'checkmark-outline'), (6, 'egg-outline'), (7, 'ellipse-outline'), (8, 'flag-outline'), (9, 'hand-left-outline'), (10, 'hand-right-outline'), (11, 'happy-outline'), (12, 'heart-outline'), (13, 'help-outline'), (14, 'information-outline'), (15, 'prism-outline'), (16, 'refresh-outline'), (17, 'remove-outline'), (18, 'sad-outline'), (19, 'search-outline'), (20, 'shapes-outline'), (21, 'square-outline'), (22, 'star-outline'), (23, 'thumbs-down-outline'), (24, 'thumbs-up-outline'), (25, 'triangle-outline'), (26, 'warning-outline'), (27, 'general-tap'), (28, 'tap'), (29, 'tap-1'), (30, 'tap-2'), (31, 'tap-3'), (32, 'swipe-left')], choices_enum=apps.tutorial.models.TutorialScenarioIconEnum, null=True)),
                ('hint_title', models.CharField(blank=True, max_length=255, null=True)),
                ('success_description', models.CharField(blank=True, max_length=255, null=True)),
                ('success_icon', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'add-outline'), (2, 'alert-outline'), (3, 'ban-outline'), (4, 'check'), (5, 'close-outline'), (33, 'checkmark-outline'), (6, 'egg-outline'), (7, 'ellipse-outline'), (8, 'flag-outline'), (9, 'hand-left-outline'), (10, 'hand-right-outline'), (11, 'happy-outline'), (12, 'heart-outline'), (13, 'help-outline'), (14, 'information-outline'), (15, 'prism-outline'), (16, 'refresh-outline'), (17, 'remove-outline'), (18, 'sad-outline'), (19, 'search-outline'), (20, 'shapes-outline'), (21, 'square-outline'), (22, 'star-outline'), (23, 'thumbs-down-outline'), (24, 'thumbs-up-outline'), (25, 'triangle-outline'), (26, 'warning-outline'), (27, 'general-tap'), (28, 'tap'), (29, 'tap-1'), (30, 'tap-2'), (31, 'tap-3'), (32, 'swipe-left')], choices_enum=apps.tutorial.models.TutorialScenarioIconEnum, null=True)),
                ('success_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reference', models.PositiveSmallIntegerField()),
                ('project_type_specifics', models.JSONField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tutorialinformationpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialinformationpage',
            name='created_by',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialinformationpage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutorialinformationpage',
            name='modified_by',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialinformationpageblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialinformationpageblock',
            name='created_by',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialinformationpageblock',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutorialinformationpageblock',
            name='modified_by',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorialinformationpage',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_pages', to='tutorial.tutorial'),
        ),
        migrations.AlterField(
            model_name='tutorialinformationpageblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tutorial.tutorialinformationpage'),
        ),
        migrations.AddConstraint(
            model_name='tutorialinformationpage',
            constraint=models.UniqueConstraint(fields=('tutorial', 'page_number'), name='unique_page_number_on_tutorial'),
        ),
        migrations.AddConstraint(
            model_name='tutorialinformationpageblock',
            constraint=models.UniqueConstraint(fields=('page', 'block_number'), name='unique_block_number_on_page'),
        ),
        migrations.AddField(
            model_name='tutorialscenariopage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorialscenariopage',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorialscenariopage',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='tutorial.tutorial'),
        ),
        migrations.AddField(
            model_name='tutorialtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorialtask',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorialtask',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tutorial.tutorialscenariopage'),
        ),
        migrations.AddConstraint(
            model_name='tutorialscenariopage',
            constraint=models.UniqueConstraint(fields=('tutorial', 'scenario_id'), name='unique_scenario_on_tutorials'),
        ),
    ]
