# Generated by Django 5.1.6 on 2025-05-22 12:32

import apps.tutorial.models
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_remove_tutorialscenariopage_unique_scenario_on_tutorials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='name',
            field=models.CharField(default='Tutorial', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='status',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Draft'), (20, 'Published'), (30, 'Archived'), (40, 'Discarded')], choices_enum=apps.tutorial.models.TutorialStatusEnum, default=10),
        ),
    ]
