# Generated by Django 5.1.6 on 2025-06-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_remove_tutorial_is_draft_tutorial_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='old_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
    ]
