# Generated by Django 5.1.6 on 2025-07-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_tutorialasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialasset',
            name='marked_as_deleted',
            field=models.BooleanField(default=False, help_text='If this flag is enabled, this project asset will be deleted in the future'),
        ),
    ]
