# Generated by Django 5.1.6 on 2025-07-31 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_alter_tutorialasset_marked_as_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialinformationpageblock',
            name='image',
        ),
        migrations.AddField(
            model_name='tutorialinformationpageblock',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tutorial.tutorialasset'),
        ),
    ]
