# Generated by Django 5.1.6 on 2025-08-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_alter_tutorialinformationpageblock_image'),
        ('tutorial', '0008_tutorial_firebase_id_tutorial_firebase_last_pushed_and_more'),
    ]

    operations = [
    ]
