# Generated by Django 5.2.4 on 2025-08-03 16:00

import apps.tutorial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_merge_20250801_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='firebase_id',
            field=models.CharField(default=apps.tutorial.models.generate_tutorial_firebase_id, max_length=40, unique=True),
        ),
    ]
