# Generated by Django 5.2.4 on 2025-08-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_alter_tutorial_firebase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialasset',
            name='external_url',
            field=models.CharField(blank=True, help_text='Provide link to the file associated with the asset', null=True),
        ),
        migrations.AlterField(
            model_name='tutorialasset',
            name='marked_as_deleted',
            field=models.BooleanField(default=False, help_text='If this flag is enabled, this asset will be deleted in the future'),
        ),
    ]
