# Generated by Django 5.2.4 on 2025-08-21 01:55

import apps.common.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0011_tutorialasset_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialasset',
            name='mimetype',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'application/geo+json'), (101, 'application/json'), (201, 'image/jpeg'), (202, 'image/png'), (203, 'image/gif'), (300, 'application/x-gzip'), (400, 'text/csv')], choices_enum=apps.common.models.AssetMimetypeEnum, null=True),
        ),
    ]
