# Generated by Django 5.2.4 on 2025-08-21 05:55

import apps.tutorial.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_alter_tutorialasset_mimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialasset',
            name='input_type',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'Image for information block')], choices_enum=apps.tutorial.models.TutorialAssetInputTypeEnum, null=True),
        ),
    ]
