# Generated by Django 5.2.4 on 2025-09-01 13:45

import apps.common.models
import django_choices_field.fields
from django.db import migrations, models
from apps.common.models import IconEnum

def set_hint_and_success(apps, schema_editor):
    Model = apps.get_model('tutorial', 'TutorialScenarioPage')
    for obj in Model.objects.all():
        obj.hint_title = obj.hint_title or '?'
        obj.hint_description = obj.hint_description or '?'
        obj.hint_icon = obj.hint_icon or IconEnum.SQUARE_OUTLINE.value
        obj.success_title = obj.success_title or '?'
        obj.success_description = obj.success_description or '?'
        obj.success_icon = obj.hint_icon or IconEnum.STAR_OUTLINE.value
        obj.save(update_fields=[
            'hint_title',
            'hint_description',
            'hint_icon',
            'success_title',
            'success_description',
            'success_icon',
        ])

class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_tutorialasset_input_type'),
    ]

    operations = [
        migrations.RunPython(set_hint_and_success, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tutorialscenariopage',
            name='hint_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorialscenariopage',
            name='hint_icon',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'add-outline'), (2, 'alert-outline'), (3, 'ban-outline'), (4, 'check'), (5, 'close-outline'), (33, 'checkmark-outline'), (6, 'egg-outline'), (7, 'ellipse-outline'), (8, 'flag-outline'), (9, 'hand-left-outline'), (10, 'hand-right-outline'), (11, 'happy-outline'), (12, 'heart-outline'), (13, 'help-outline'), (14, 'information-outline'), (15, 'prism-outline'), (16, 'refresh-outline'), (17, 'remove-outline'), (18, 'sad-outline'), (19, 'search-outline'), (20, 'shapes-outline'), (21, 'square-outline'), (22, 'star-outline'), (23, 'thumbs-down-outline'), (24, 'thumbs-up-outline'), (25, 'triangle-outline'), (26, 'warning-outline'), (27, 'general-tap'), (28, 'tap'), (29, 'tap-1'), (30, 'tap-2'), (31, 'tap-3'), (32, 'swipe-left')], choices_enum=apps.common.models.IconEnum),
        ),
        migrations.AlterField(
            model_name='tutorialscenariopage',
            name='hint_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorialscenariopage',
            name='success_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorialscenariopage',
            name='success_icon',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'add-outline'), (2, 'alert-outline'), (3, 'ban-outline'), (4, 'check'), (5, 'close-outline'), (33, 'checkmark-outline'), (6, 'egg-outline'), (7, 'ellipse-outline'), (8, 'flag-outline'), (9, 'hand-left-outline'), (10, 'hand-right-outline'), (11, 'happy-outline'), (12, 'heart-outline'), (13, 'help-outline'), (14, 'information-outline'), (15, 'prism-outline'), (16, 'refresh-outline'), (17, 'remove-outline'), (18, 'sad-outline'), (19, 'search-outline'), (20, 'shapes-outline'), (21, 'square-outline'), (22, 'star-outline'), (23, 'thumbs-down-outline'), (24, 'thumbs-up-outline'), (25, 'triangle-outline'), (26, 'warning-outline'), (27, 'general-tap'), (28, 'tap'), (29, 'tap-1'), (30, 'tap-2'), (31, 'tap-3'), (32, 'swipe-left')], choices_enum=apps.common.models.IconEnum),
        ),
        migrations.AlterField(
            model_name='tutorialscenariopage',
            name='success_title',
            field=models.CharField(max_length=255),
        ),
    ]
