# Generated by Django 5.2.4 on 2025-09-01 13:35

import apps.tutorial.models
import django.core.files.storage
import main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_tutorialasset_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialasset',
            name='file',
            field=main.fields.OverwritableFileField(help_text='The file associated with the asset', max_length=255, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=apps.tutorial.models.UploadHelper.tutorial_asset),
        ),
    ]
