# Generated by Django 5.2.4 on 2025-09-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0014_alter_tutorialasset_file'),
        ('tutorial', '0014_alter_tutorialscenariopage_hint_description_and_more'),
    ]

    operations = [
    ]
