# Generated by Django 5.2.5 on 2025-09-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0015_merge_20250902_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='status_message',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
