
x-server: &base_server_setup
  build:
    context: ./
    tags:
      - mapswipe/mapswipe-backend:${DOCKER_TAG:-latest}
  # Used for python debugging.
  stdin_open: true
  tty: true
  environment: &base_server_environments
    DEBUG: ${DEBUG:-true}
    ENABLE_DEBUG_TOOLBAR: ${ENABLE_DEBUG_TOOLBAR:-true}
    APP_ENVIRONMENT: ${APP_ENVIRONMENT:-DEV}
    SECRET_KEY: ${SECRET_KEY:?error}
    # Domain configs
    APP_DOMAIN: ${APP_DOMAIN:-http://localhost:8000}
    FRONTEND_DOMAIN: ${FRONTEND_DOMAIN:-http://localhost:3000}  # NOTE: Not used right now
    SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN:-localhost}
    CSRF_COOKIE_DOMAIN: ${CSRF_COOKIE_DOMAIN:-localhost}
    # Postgres
    POSTGRES_DB: ${POSTGRES_DB:-mapswipe}
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    POSTGRES_HOST: ${POSTGRES_HOST:-db}
    POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    # Redis
    CELERY_REDIS_URL: ${CELERY_REDIS_URL:-redis://redis:6379/0}
    CACHE_REDIS_URL: ${CACHE_REDIS_URL:-redis://redis:6379/1}
    TEST_CACHE_REDIS_URL: ${TEST_CACHE_REDIS_URL:-redis://redis:6379/11}
    # Email (Using mailpit)
    EMAIL_HOST: ${EMAIL_HOST:-mailpit}
    EMAIL_PORT: ${EMAIL_PORT:-1025}
    EMAIL_USE_TLS: ${EMAIL_USE_TLS:-false}
    EMAIL_HOST_USER: ${EMAIL_HOST_USER:-mailpit}
    EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD:-mailpit}
    DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL:-Mapswipe Dev <dev@mapswipe.org>}
    # Map Image keys (Dummy values)
    MAP_IMAGE_BING_API_KEY: ${MAP_IMAGE_BING_API_KEY:-dummy-bing}
    MAP_IMAGE_MAPBOX_API_KEY: ${MAP_IMAGE_MAPBOX_API_KEY:-dummy-mapbox}
    MAP_IMAGE_MAXAR_STANDARD_API_KEY: ${MAP_IMAGE_MAXAR_STANDARD_API_KEY:-dummy-maxar-standard}
    MAP_IMAGE_MAXAR_PREMIUM_API_KEY: ${MAP_IMAGE_MAXAR_PREMIUM_API_KEY:-dummy-maxar-premium}
    MAP_IMAGE_ESRI_API_KEY: ${MAP_IMAGE_ESRI_API_KEY:-dummy-esri}
    MAP_IMAGE_ESRI_BETA_API_KEY: ${MAP_IMAGE_ESRI_BETA_API_KEY:-dummy-esri-beta}
    # MAP_IMAGE_DIGITAL_GLOBE_API_KEY: ${MAP_IMAGE_DIGITAL_GLOBE_API_KEY:-dummy-digital-globe}
    OSMCHA_API_KEY: ${OSMCHA_API_KEY:-dummy-osmcha-api-key}
    # Firebase
    FIREBASE_EMULATOR_USE: ${FIREBASE_EMULATOR_USE:-true}
    FIREBASE_EMULATOR_PROJECT_ID: ${FIREBASE_EMULATOR_PROJECT_ID:-dev-mapswipe}
    FIREBASE_EMULATOR_DATABASE_HOST: ${FIREBASE_EMULATOR_DATABASE_HOST:-firebase:9000}
  env_file:
    - path: ${BACKEND_ENV_FILE:-.env}
      required: false
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./:/code/
    - ipython_data_local:/root/.ipython/profile_default   # persist ipython data, including ipython history
  depends_on:
    - db
    - redis
    - mailpit
    - firebase

x-worker: &base_worker_setup
  <<: *base_server_setup
  restart: unless-stopped
  environment:
    <<: *base_server_environments
    APP_TYPE: "WORKER-BEAT"

services:
  db:
    image: postgis/postgis:17-3.5
    ports:
      - 127.0.0.1:${MAPSWIPE_DB_EXPOSE_PORT:-5432}:5432
    environment:
      POSTGRES_DB: mapswipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data17:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  firebase:
    build:
      context: ./firebase/
    stop_grace_period: 30s
    tty: true
    entrypoint: ["./docker_entrypoint.sh"]
    environment:
      FIREBASE_EMULATOR_DATA_DIR: "/data/emulator"
    volumes:
      - ./firebase:/firebase
      - ./.data/firebase:/data/
    ports:
      - "127.0.0.1:4000:4000" # ui
      - "127.0.0.1:4400:4400" # hub
      - "127.0.0.1:4600:4600" # logging
      - "127.0.0.1:9000:9000" # database
      - "127.0.0.1:9099:9099" # auth
      - "127.0.0.1:5001:5001" # functions

  mailpit:
      image: axllent/mailpit:latest
      restart: unless-stopped
      ports:
        - 127.0.0.1:8025:8025  # Web
      environment:
        MP_MAX_MESSAGES: 200
        MP_DATA_FILE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
      volumes:
        - mailpit_data:/data

  web:
    <<: *base_server_setup
    command: ["/code/misc/dev/run_web.sh"]
    environment:
      <<: *base_server_environments
      APP_TYPE: "WEB"
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
      - redis

  worker-beat:
    <<: *base_worker_setup
    command: bash -c "/code/misc/dev/run_worker_beat.sh"

  worker:
    <<: *base_worker_setup
    command: bash -c "/code/misc/dev/run_worker.sh"
    healthcheck:
      test: ["CMD-SHELL", "celery -A main inspect ping -d celery@$$HOSTNAME || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  postgres_data17:
  redis_data:
  mailpit_data:
  ipython_data_local:
