# Generated by Django 5.1.6 on 2025-03-06 09:50

import apps.contributor.models
import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=30)),
                ('username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('old_user_group_id', models.CharField(db_index=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributorUserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributor.contributoruser')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributor.contributorusergroup')),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroupMembershipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Join'), (2, 'Leave')], choices_enum=apps.contributor.models.ContributorUserGroupMembershipLogAction)),
                ('date', models.DateTimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributor.contributorusergroupmembership')),
            ],
        ),
    ]
