# Generated by Django 5.1.6 on 2025-05-15 10:29

import apps.common.models
import apps.contributor.models
import django.db.models.manager
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='Firebase User ID', max_length=30, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=26, unique=True, validators=[apps.common.models.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('old_id', models.CharField(db_index=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroupMembershipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Join'), (2, 'Leave')], choices_enum=apps.contributor.models.ContributorUserGroupMembershipLogActionEnum)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
