# Generated by Django 5.2.5 on 2025-09-10 17:23

import django.db.models.manager
import django_choices_field.fields
import ulid
import utils.common
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_id', models.CharField(default=ulid.ULID, max_length=30, unique=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('name', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('username', models.CharField(max_length=255)),
                ('firebase_id', models.CharField(help_text='Firebase User ID (External)', max_length=30, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_id', models.CharField(default=ulid.ULID, max_length=30, unique=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroupMembershipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Join'), (2, 'Leave')])),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContributorUserGroupMembershipLogTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(max_length=255)),
                ('contributor_user_group_firebase_id', models.CharField(max_length=255)),
                ('contributor_user_firebase_id', models.CharField(max_length=255)),
                ('action', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Join'), (2, 'Leave')])),
                ('date', models.DateTimeField()),
                ('contributor_user_group_id', models.BigIntegerField(blank=True, null=True)),
                ('contributor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('is_firebase_mapping_valid', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
