# Generated by Django 5.1.6 on 2025-04-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributorusergroup',
            old_name='old_user_group_id',
            new_name='old_id',
        ),
    ]
