# Generated by Django 5.1.6 on 2025-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0003_rename_old_user_group_id_contributorusergroup_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributoruser',
            name='user_id',
            field=models.CharField(db_index=True, help_text='Firebase User ID', max_length=30),
        ),
    ]
