# Generated by Django 5.1.6 on 2025-07-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0004_contributorteam_contributoruser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributoruser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='contributor.contributorteam'),
        ),
    ]
