# Generated by Django 5.1.6 on 2025-05-12 11:02

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0005_alter_contributorusergroup_archived_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contributorusergroup',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contributoruser',
            name='user_id',
            field=models.CharField(db_index=True, help_text='Firebase User ID', max_length=30, unique=True),
        ),
    ]
