# Generated by Django 5.2.4 on 2025-07-30 04:23

import apps.common.models
import django_choices_field.fields
import uuid
from django.db import migrations, models


def assign_unique_tokens(apps, schema_editor):
    ContributorTeam = apps.get_model('contributor', 'ContributorTeam')
    for obj in ContributorTeam.cte_objects.all():
        obj.token = uuid.uuid4()
        obj.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0005_alter_contributoruser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorteam',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when project was pushed to firebase', null=True),
        ),
        migrations.AddField(
            model_name='contributorteam',
            name='firebase_push_status',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], choices_enum=apps.common.models.FirebasePushStatusEnum, null=True),
        ),
        migrations.AddField(
            model_name='contributorteam',
            name='old_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contributorteam',
            name='token',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(assign_unique_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contributorteam',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
