# Generated by Django 5.2.4 on 2025-07-24 10:45

import apps.common.models
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0005_alter_contributoruser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorteam',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when project was pushed to firebase', null=True),
        ),
        migrations.AddField(
            model_name='contributorteam',
            name='firebase_push_status',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], choices_enum=apps.common.models.FirebasePushStatusEnum, null=True),
        ),
    ]
