# Generated by Django 5.1.6 on 2025-07-30 10:27

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0006_contributorteam_firebase_last_pushed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorteam',
            name='canonical_id',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('old_id'), django.db.models.functions.comparison.Cast(models.F('id'), models.CharField())), output_field=models.CharField(), unique=True),
        ),
    ]
