# Generated by Django 5.2.4 on 2025-07-30 11:30

import apps.common.models
import django.db.models.functions.comparison
import django.db.models.manager
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0007_contributorteam_canonical_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contributoruser',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contributoruser',
            name='old_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contributoruser',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when project was pushed to firebase', null=True),
        ),
        migrations.AddField(
            model_name='contributoruser',
            name='firebase_push_status',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], choices_enum=apps.common.models.FirebasePushStatusEnum, null=True),
        ),
        migrations.AddField(
            model_name='contributoruser',
            name='canonical_id',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('old_id'), django.db.models.functions.comparison.Cast(models.F('id'), models.CharField())), output_field=models.CharField(), unique=True),
        ),
    ]
