# Generated by Django 5.1.6 on 2025-08-01 06:05

import apps.common.models
import django_choices_field.fields
from django.db import migrations, models
from ulid import ULID

def set_firebase_id_for_team(apps, schema_editor):
    Model = apps.get_model('contributor', 'ContributorTeam')
    for obj in Model.cte_objects.all():
        obj.firebase_id = str(ULID())
        obj.save(update_fields=['firebase_id'])

def set_firebase_id_for_user(apps, schema_editor):
    Model = apps.get_model('contributor', 'ContributorUser')
    for obj in Model.cte_objects.all():
        obj.firebase_id = str(ULID())
        obj.save(update_fields=['firebase_id'])

def set_firebase_id_for_user_group(apps, schema_editor):
    Model = apps.get_model('contributor', 'ContributorUserGroup')
    for obj in Model.cte_objects.all():
        obj.firebase_id = str(ULID())
        obj.save(update_fields=['firebase_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0008_alter_contributoruser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributorteam',
            name='canonical_id',
        ),
        migrations.RemoveField(
            model_name='contributoruser',
            name='canonical_id',
        ),
        migrations.AddField(
            model_name='contributorteam',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contributoruser',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contributorusergroup',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contributorusergroup',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True),
        ),
        migrations.AddField(
            model_name='contributorusergroup',
            name='firebase_push_status',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], choices_enum=apps.common.models.FirebasePushStatusEnum, null=True),
        ),
        migrations.AlterField(
            model_name='contributorteam',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True),
        ),
        migrations.AlterField(
            model_name='contributoruser',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True),
        ),
        migrations.AlterField(
            model_name='contributorusergroup',
            name='old_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.RunPython(set_firebase_id_for_team, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_firebase_id_for_user, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_firebase_id_for_user_group, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contributorteam',
            name='firebase_id',
            field=models.CharField(default=ULID, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='contributoruser',
            name='firebase_id',
            field=models.CharField(default=ULID, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='contributorusergroup',
            name='firebase_id',
            field=models.CharField(default=ULID, max_length=30, unique=True),
        ),
    ]
