# Generated by Django 5.2.4 on 2025-08-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0009_remove_contributorteam_canonical_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributoruser',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='contributoruser',
            name='firebase_id',
            field=models.CharField(help_text='Firebase User ID (External)', max_length=30, unique=True),
        ),
    ]
