# Generated by Django 5.2.4 on 2025-08-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0010_remove_contributoruser_user_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributorusergroupmembership',
            unique_together={('user_group', 'user')},
        ),
    ]
