# Generated by Django 5.2.4 on 2025-08-31 09:53

import apps.contributor.models
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0011_alter_contributorusergroupmembership_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorUserGroupMembershipLogTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(max_length=255)),
                ('contributor_user_group_firebase_id', models.CharField(max_length=255)),
                ('contributor_user_firebase_id', models.CharField(max_length=255)),
                ('action', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Join'), (2, 'Leave')], choices_enum=apps.contributor.models.ContributorUserGroupMembershipLogActionEnum)),
                ('date', models.DateTimeField()),
                ('contributor_user_group_id', models.BigIntegerField(blank=True, null=True)),
                ('contributor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('is_firebase_mapping_valid', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
