# Generated by Django 5.2.5 on 2025-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
