# Generated by Django 5.1.6 on 2025-06-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
    ]
