# Generated by Django 5.1.6 on 2025-06-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_uid',
            field=models.CharField(blank=True, help_text='firebase user uuid', max_length=50, null=True, unique=True),
        ),
    ]
