# Generated by Django 5.2.5 on 2025-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_slack_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
