# Generated by Django 5.1.6 on 2025-07-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_fb_uid'),
        ('user', '0002_user_old_id'),
    ]

    operations = [
    ]
