# Generated by Django 5.2.5 on 2025-10-08 08:47

from django.db import migrations, models

def update_null_to_empty_string(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User.objects.filter(slack_user_id__isnull=True).update(slack_user_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_slack_user_id'),
    ]

    operations = [
        migrations.RunPython(update_null_to_empty_string, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
