# Generated by Django 5.2.4 on 2025-08-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0011_alter_contributorusergroupmembership_unique_together'),
        ('user', '0003_merge_0002_user_fb_uid_0002_user_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fb_uid',
        ),
        migrations.AddField(
            model_name='user',
            name='contributor_user',
            field=models.ForeignKey(blank=True, help_text='The Contributor user associated with this User. This will also be used for authentication using firebase.', null=True, on_delete=django.db.models.deletion.PROTECT, to='contributor.contributoruser', unique=True),
        ),
    ]
