# Generated by Django 5.2.4 on 2025-08-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_fb_uid_user_contributor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_id',
        ),
    ]
