# Generated by Django 5.2.4 on 2025-08-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
