# Generated by Django 5.2.5 on 2025-09-04 17:46

import django.core.files.storage
import django_choices_field.fields
import main.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalExportAsset',
            fields=[
                ('type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Project Type Aggregates'), (2, 'All projects'), (3, 'Projects geojson with centroid'), (4, 'Projects Geojson with GEOM')], primary_key=True, serialize=False)),
                ('file_size', models.PositiveIntegerField(help_text='The size of the file in bytes')),
                ('file', main.fields.OverwritableFileField(blank=True, help_text='The file associated with the asset', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to='global/asset/')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
