# Generated by Django 5.2.5 on 2025-09-10 17:23

import django.core.files.storage
import django.db.models.manager
import django_choices_field.fields
import main.fields
import ulid
import utils.common
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_id', models.CharField(default=ulid.ULID, max_length=30, unique=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('text', models.TextField()),
                ('url', models.URLField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalExportAsset',
            fields=[
                ('type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Project Type Aggregates'), (2, 'All projects'), (3, 'Projects geojson with centroid'), (4, 'Projects Geojson with GEOM')], primary_key=True, serialize=False)),
                ('file_size', models.PositiveIntegerField(help_text='The size of the file in bytes')),
                ('file', main.fields.OverwritableFileField(blank=True, help_text='The file associated with the asset', max_length=255, null=True, upload_to='global/asset/')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
