# Generated by Django 5.2.5 on 2026-02-17 12:03

import ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='firebase_id',
            field=models.CharField(default=ulid.ULID, max_length=36, unique=True),
        ),
    ]
