# Generated by Django 5.1.6 on 2025-05-12 11:02

import apps.community_dashboard.models
import django.db.models.deletion
import django.db.models.manager
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributor', '0006_alter_contributorusergroup_managers_and_more'),
        ('project', '0012_alter_organization_managers_alter_project_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', django_choices_field.fields.IntegerChoicesField(choices=[(0, 'Contributor User Data Latest Date'), (1, 'Contributor UserGroup Stat Data Latest Date')], choices_enum=apps.community_dashboard.models.AggregatedTrackingTypeEnum, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='Represents the date before which data is synced to aggregated tables.', max_length=225, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedUserGroupStatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_date', models.DateField()),
                ('total_time', models.IntegerField()),
                ('task_count', models.FloatField()),
                ('swipes', models.FloatField()),
                ('area_swiped', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contributor.contributoruser')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contributor.contributorusergroup')),
            ],
            options={
                'unique_together': {('project', 'user', 'user_group', 'timestamp_date')},
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedUserStatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_date', models.DateField()),
                ('total_time', models.IntegerField()),
                ('task_count', models.IntegerField()),
                ('swipes', models.IntegerField()),
                ('area_swiped', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contributor.contributoruser')),
            ],
            options={
                'unique_together': {('project', 'user', 'timestamp_date')},
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
