# Generated by Django 5.2.5 on 2025-09-10 17:23

import django.db.models.manager
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', django_choices_field.fields.IntegerChoicesField(choices=[(0, 'Contributor User Data Latest Date'), (1, 'Contributor UserGroup Stat Data Latest Date')], unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='Represents the date before which data is synced to aggregated tables.', max_length=225, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedUserGroupStatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_date', models.DateField()),
                ('total_time', models.IntegerField()),
                ('task_count', models.FloatField()),
                ('swipes', models.FloatField()),
                ('area_swiped', models.FloatField()),
            ],
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedUserStatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_date', models.DateField()),
                ('total_time', models.IntegerField()),
                ('task_count', models.IntegerField()),
                ('swipes', models.IntegerField()),
                ('area_swiped', models.FloatField()),
            ],
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
