# Generated by Django 5.2.5 on 2025-09-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community_dashboard', '0001_initial'),
        ('contributor', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedusergroupstatdata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project'),
        ),
        migrations.AddField(
            model_name='aggregatedusergroupstatdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contributor.contributoruser'),
        ),
        migrations.AddField(
            model_name='aggregatedusergroupstatdata',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contributor.contributorusergroup'),
        ),
        migrations.AddField(
            model_name='aggregateduserstatdata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project'),
        ),
        migrations.AddField(
            model_name='aggregateduserstatdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contributor.contributoruser'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedusergroupstatdata',
            unique_together={('project', 'user', 'user_group', 'timestamp_date')},
        ),
        migrations.AlterUniqueTogether(
            name='aggregateduserstatdata',
            unique_together={('project', 'user', 'timestamp_date')},
        ),
    ]
