# Generated by Django 5.1.6 on 2025-04-01 16:30

import apps.project.models
import django.contrib.gis.db.models.fields
import django.db.models.functions.text
import django_choices_field.fields
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('unique_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Lower('name'), output_field=models.CharField(), unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('old_project_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('is_draft', models.BooleanField(default=True, help_text='Draft project can be modified')),
                ('project_type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Find'), (3, 'Compare'), (4, 'Completeness')], choices_enum=apps.project.models.ProjectTypeEnum)),
                ('image', models.FileField(upload_to=apps.project.models.UploadHelper.project_image)),
                ('project_type_specifics', models.JSONField(blank=True)),
                ('zoom_level', models.PositiveSmallIntegerField()),
                ('group_size', models.PositiveSmallIntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('look_for', models.CharField(help_text='eg: Buildings and Roads', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry_file', models.FileField(blank=True, null=True, upload_to=apps.project.models.UploadHelper.project_geometry)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[utils.fields.validate_percentage])),
                ('required_results', models.IntegerField(default=0)),
                ('result_count', models.IntegerField(default=0)),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Private finished'), (4, 'Archived'), (5, 'Finished')], choices_enum=apps.project.models.ProjectStatusEnum, default=1)),
                ('verification_number', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, dim=3, null=True, srid=4326)),
                ('project_type_specifics', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tasks', models.IntegerField()),
                ('required_count', models.IntegerField()),
                ('finished_count', models.IntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[utils.fields.validate_percentage])),
                ('project_type_specifics', models.JSONField()),
                ('total_area', models.FloatField(default=None, null=True)),
                ('time_spent_max_allowed', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
