# Generated by Django 5.1.6 on 2025-03-06 09:50

import apps.project.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django_choices_field.fields
import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=4326)),
                ('project_type_specifics', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tasks', models.IntegerField()),
                ('required_count', models.IntegerField()),
                ('finished_count', models.IntegerField(default=0)),
                ('progress', utils.fields.PercentageField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('project_type_specifics', models.JSONField()),
                ('total_area', models.FloatField(default=None, null=True)),
                ('time_spent_max_allowed', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('unique_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Lower('name'), output_field=models.CharField(), unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('old_project_id', models.CharField(db_index=True, max_length=30, null=True)),
                ('is_draft', models.BooleanField(default=True, help_text='Draft project can be modified')),
                ('project_type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Find'), (2, 'Validate'), (3, 'Compare'), (4, 'Completeness'), (5, 'Media'), (6, 'Digitization'), (7, 'Street')], choices_enum=apps.project.models.ProjectType)),
                ('image', models.FileField(upload_to=apps.project.models.UploadHelper.project_image)),
                ('project_type_specifics', models.JSONField()),
                ('is_featured', models.BooleanField(default=False)),
                ('look_for', models.CharField(help_text='eg: Buildings and Roads', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=4326)),
                ('progress', utils.fields.PercentageField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('required_results', models.IntegerField()),
                ('result_count', models.IntegerField()),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Private finished'), (4, 'Archived'), (5, 'Finished')], choices_enum=apps.project.models.ProjectStatus)),
                ('verification_number', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Which group, institution or community is requesting this project?', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='project.organization')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
