# Generated by Django 5.2.5 on 2025-09-10 17:23

import apps.project.models
import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import UnaccentExtension
import django.core.files.storage
import django.db.models.functions.text
import django.db.models.manager
import django_choices_field.fields
import main.fields
import ulid
import utils.common
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        UnaccentExtension(),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('total_area', models.FloatField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_id', models.CharField(default=ulid.ULID, max_length=30, unique=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('unique_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Lower('name'), output_field=models.CharField(), unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_id', models.CharField(default=ulid.ULID, max_length=30, unique=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('project_type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Find'), (2, 'Validate'), (10, 'Validate Image'), (3, 'Compare'), (4, 'Completeness'), (7, 'Street')])),
                ('topic', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('project_number', models.PositiveIntegerField()),
                ('look_for', models.CharField(blank=True, help_text='What should the users look for (e.g. buildings, cars, trees)', max_length=255, null=True)),
                ('additional_info_url', models.CharField(blank=True, help_text='Provide an optional link to a resource with additional information on the project', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_instruction', models.TextField(blank=True, help_text='Provide project instruction', null=True)),
                ('verification_number', models.PositiveSmallIntegerField(default=3, help_text='How many people do you want to see every tile before you consider it finished?')),
                ('group_size', models.PositiveSmallIntegerField(default=10, help_text='How big should a mapping session be? Group size refers to the number of tasks per mapping session.')),
                ('max_tasks_per_user', models.PositiveSmallIntegerField(blank=True, default=10, help_text='How many tasks each user is allowed to work on for this project', null=True)),
                ('project_type_specifics', models.JSONField(blank=True, null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('total_area', models.FloatField(default=None, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Draft'), (20, 'Ready to Process'), (80, 'Discarded'), (30, 'Processing Failed'), (40, 'Processed'), (45, 'Ready to Publish'), (46, 'Publishing Failed'), (50, 'Published'), (60, 'Paused'), (70, 'Withdrawn'), (75, 'Finished')], default=10)),
                ('processing_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(10, 'Preparing'), (20, 'Validating Geometry'), (30, 'Generating groups and tasks'), (40, 'Analyzing groups and tasks'), (50, 'Generating GeoJSON from tasks'), (60, 'Processing Completed')], null=True)),
                ('status_message', models.CharField(blank=True, max_length=510, null=True)),
                ('required_results', models.IntegerField(default=0)),
                ('result_count', models.IntegerField(default=0)),
                ('progress_status', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'On going'), (2, 'Completed')], default=1)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Percentage of the required contribution that has been completed', validators=[utils.fields.validate_percentage])),
                ('number_of_contributor_users', models.PositiveIntegerField(default=0, help_text='Number of users who made contributions to this project')),
                ('number_of_results', models.PositiveIntegerField(default=0, help_text='Number of results contributed to this project')),
                ('number_of_results_for_progress', models.PositiveIntegerField(default=0, help_text='Number of results contributed to this project that can be used to calculate the progress of this project. Max no. of results per task that can be used to calculate progress is equal to the `verification number`')),
                ('last_contribution_date', models.DateField(blank=True, help_text='Last recent contribution date', null=True)),
            ],
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=26, unique=True, validators=[utils.common.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', django_choices_field.fields.IntegerChoicesField(choices=[(100, 'Input'), (200, 'Output'), (300, 'Export'), (400, 'Debug')])),
                ('mimetype', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'application/geo+json'), (101, 'application/json'), (201, 'image/jpeg'), (202, 'image/png'), (203, 'image/gif'), (300, 'application/x-gzip'), (400, 'text/csv'), (500, 'text/plain')], null=True)),
                ('file_size', models.PositiveIntegerField(help_text='The size of the file in bytes')),
                ('marked_as_deleted', models.BooleanField(default=False, help_text='If this flag is enabled, this asset will be deleted in the future')),
                ('external_url', models.CharField(blank=True, help_text='Provide link to the file associated with the asset', null=True)),
                ('export_type', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'Aggregated Results (CSV)'), (101, 'Aggregated Results (with Geometry) (GEOJSON)'), (104, 'Groups (CSV)'), (105, 'History (CSV)'), (106, 'Results (CSV)'), (107, 'Tasks (CSV)'), (108, 'Users (CSV)'), (109, 'Area of Interest (GEOJSON)'), (200, 'HOT Tasking Manager Geometries (GEOJSON)'), (201, 'Moderate to High Agreement Yes Maybe Geometries (GEOJSON)')], null=True)),
                ('input_type', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'AOI Geometry'), (200, 'Image with object annotations'), (201, 'Image for project cover')], null=True)),
                ('file', main.fields.OverwritableFileField(blank=True, help_text='The file associated with the asset', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=apps.project.models.UploadHelper.project_asset)),
                ('asset_type_specifics', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('firebase_id', models.CharField(max_length=30)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=4326)),
                ('project_type_specifics', models.JSONField()),
            ],
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('firebase_push_status', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], null=True)),
                ('firebase_last_pushed', models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True)),
                ('firebase_id', models.CharField(max_length=30)),
                ('number_of_tasks', models.IntegerField()),
                ('required_count', models.IntegerField()),
                ('finished_count', models.IntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[utils.fields.validate_percentage])),
                ('project_type_specifics', models.JSONField()),
                ('total_area', models.FloatField(default=None, null=True)),
                ('time_spent_max_allowed', models.FloatField(default=None, null=True)),
            ],
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
