# Generated by Django 5.1.6 on 2025-03-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tutorial',
            field=models.ForeignKey(blank=True, help_text='Tutorial used for this project.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tutorial.tutorial'),
        ),
        migrations.AddField(
            model_name='projecttaskgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.projecttaskgroup'),
        ),
    ]
