# Generated by Django 5.2.5 on 2025-09-10 17:23

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributor', '0002_initial'),
        ('project', '0001_initial'),
        ('tutorial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='aoi_geometry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.geometry'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='requesting_organization',
            field=models.ForeignKey(help_text='Which group, institution or community is requesting this project?', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='project.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contributor.contributorteam'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(models.Q(('team__isnull', False)), output_field=models.BooleanField()), help_text='If the project is private, then it is only visible to the team members.', output_field=models.BooleanField())
        ),
        migrations.AddField(
            model_name='project',
            name='tutorial',
            field=models.ForeignKey(blank=True, help_text='Tutorial used for this project.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tutorial.tutorial'),
        ),
        migrations.AddField(
            model_name='projectasset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectasset',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='aoi_geometry_input_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.projectasset'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.projectasset'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_specific_output_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.projectasset'),
        ),
        migrations.AddField(
            model_name='projecttaskgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.projecttaskgroup'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('topic'), django.db.models.functions.text.Lower('region'), models.F('project_number'), models.F('requesting_organization'), name='unique_project_name', violation_error_message='A project with the same topic, region, project number and requesting organization already exists.'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttaskgroup',
            unique_together={('project', 'firebase_id')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttask',
            unique_together={('task_group', 'firebase_id')},
        ),
    ]
