# Generated by Django 5.2.5 on 2025-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_thread_ts',
            field=models.CharField(blank=True, help_text='Timestamp of the base slack message', max_length=20, null=True),
        ),
    ]
