# Generated by Django 5.1.6 on 2025-05-16 08:29

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='client_id',
            field=models.CharField(max_length=26, unique=True, validators=[apps.common.models.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_id',
            field=models.CharField(max_length=26, unique=True, validators=[apps.common.models.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='client_id',
            field=models.CharField(max_length=26, unique=True, validators=[apps.common.models.validate_ulid]),
        ),
    ]
