# Generated by Django 5.1.6 on 2025-04-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='old_project_id',
            new_name='old_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='zoom_level',
        ),
        migrations.AddField(
            model_name='project',
            name='additional_info_url',
            field=models.CharField(blank=True, help_text='Provide an optional link to a resource with additional information on the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_tasks_per_user',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many tasks each user is allowed to work on for this project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='group_size',
            field=models.PositiveSmallIntegerField(help_text='How big should a mapping session be? Group size refers to the number of tasks per mapping session.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='look_for',
            field=models.CharField(help_text='What should the users look for (e.g. buildings, cars, trees)', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='verification_number',
            field=models.PositiveSmallIntegerField(help_text='How many people do you want to see every tile before you consider it finished?'),
        ),
    ]
