# Generated by Django 5.2.5 on 2025-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_slack_thread_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_tasks_per_user',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many tasks each user is allowed to work on for this project', null=True),
        ),
    ]
