# Generated by Django 5.2.5 on 2025-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_slack_thread_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_progress_notifications',
            field=models.PositiveIntegerField(help_text='Stores the last progress checkpoint notified via Slack.', null=True),
        ),
    ]
