# Generated by Django 5.1.6 on 2025-05-29 10:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_organization_client_id_alter_project_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
