# Generated by Django 5.1.6 on 2025-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_old_project_id_project_old_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='old_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projecttaskgroup',
            name='old_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
    ]
