# Generated by Django 5.2.5 on 2025-09-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_slack_thread_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_progress_notifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
