# Generated by Django 5.1.6 on 2025-06-19 10:02

import apps.project.models
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projecttask_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when project was pushed to firebase', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='firebase_push_status',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], choices_enum=apps.common.models.FirebasePushStatusEnum, null=True),
        ),
    ]
