# Generated by Django 5.1.6 on 2025-04-22 04:46

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projecttask_old_id_projecttaskgroup_old_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='organization',
            new_name='requesting_organization',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='geometry_file',
            new_name='aoi_geometry_file',
        ),
        migrations.AlterField(
            model_name='project',
            name='aoi_geometry_file',
            field=models.FileField(blank=True, help_text='The area of interest for this project uploaded by the user. This should be OGR-supported vector geospatial file format', null=True, upload_to=apps.project.models.UploadHelper.project_asset),
        ),
        migrations.AddField(
            model_name='project',
            name='processed_geometry_file',
            field=models.FileField(blank=True, help_text='Eg. For TileMapService, this includes the AOI broken down into tiles.', null=True, upload_to=apps.project.models.UploadHelper.project_asset),
        ),
    ]
