# Generated by Django 5.2.5 on 2025-10-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_project_type'),
        ('project', '0004_project_slack_progress_notifications'),
    ]

    operations = [
    ]
