# Generated by Django 5.1.6 on 2025-06-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0004_contributorteam_contributoruser_team'),
        ('project', '0004_alter_projecttask_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contributor.contributorteam'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(models.Q(('team__isnull', False)), output_field=models.BooleanField()), help_text='If the project is private, then it is only visible to the team members.', output_field=models.BooleanField()),
        ),
    ]
