# Generated by Django 5.1.6 on 2025-04-23 08:08

import apps.project.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_organization_project_requesting_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='processing_status',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Waiting'), (20, 'Preparing'), (30, 'Validating Geometry'), (40, 'Generating groups and tasks'), (50, 'Analyzing groups and tasks'), (60, 'Generating GeoJSON from tasks'), (70, 'Processing Completed')], choices_enum=apps.project.models.ProjectProcessingStatusEnum, default=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Draft'), (20, 'Marked as Ready'), (30, 'Failed'), (40, 'Ready'), (50, 'Published'), (60, 'Paused'), (70, 'Archived'), (80, 'Discarded')], choices_enum=apps.project.models.ProjectStatusEnum, default=10),
        ),
    ]
