# Generated by Django 5.2.5 on 2025-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_merge_20251001_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slack_progress_notifications',
            field=models.PositiveIntegerField(blank=True, help_text='Stores the last progress checkpoint notified via Slack.', null=True),
        ),
    ]
