# Generated by Django 5.1.6 on 2025-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_team_project_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='file_size',
            field=models.PositiveIntegerField(default=1, help_text='The size of the file in bytes'),
            preserve_default=False,
        ),
    ]
