# Generated by Django 5.2.5 on 2025-10-07 16:17

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0002_initial'),
        ('project', '0006_alter_project_max_tasks_per_user'),
        ('tutorial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_name',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(models.F('project_type'), django.db.models.functions.text.Lower('topic'), django.db.models.functions.text.Lower('region'), models.F('project_number'), models.F('requesting_organization'), name='unique_project_name', violation_error_message='A project with the same type, topic, region, project number and requesting organization already exists.'),
        ),
    ]
