# Generated by Django 5.1.6 on 2025-04-23 09:17

import apps.project.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_processing_status_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='processing_status',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(10, 'Preparing'), (20, 'Validating Geometry'), (30, 'Generating groups and tasks'), (40, 'Analyzing groups and tasks'), (50, 'Generating GeoJSON from tasks'), (60, 'Processing Completed')], choices_enum=apps.project.models.ProjectProcessingStatusEnum, null=True),
        ),
    ]
