# Generated by Django 5.1.6 on 2025-07-15 05:51

from django.db.models.functions import Concat
from django.db import migrations, models


def update_tasks(apps, schema_editor):
    ProjectTask = apps.get_model('project', 'ProjectTask')
    ProjectTask.objects.annotate(
        generated_id=Concat(models.Value("legacy_"), models.F("id")),
    ).update(legacy_task_id=models.F("generated_id"))


def update_groups(apps, schema_editor):
    ProjectTaskGroup = apps.get_model('project', 'ProjectTaskGroup')
    ProjectTaskGroup.objects.annotate(
        generated_id=Concat(models.Value("legacy_"), models.F("id")),
    ).update(legacy_group_id=models.F("generated_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_team_project_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='legacy_task_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projecttaskgroup',
            name='legacy_group_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.RunPython(update_tasks, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_groups, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projecttask',
            name='legacy_task_id',
            field=models.CharField(db_index=True, default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttaskgroup',
            name='legacy_group_id',
            field=models.CharField(db_index=True, default=None, max_length=30),
            preserve_default=False,
        ),
    ]
