# Generated by Django 5.2.5 on 2025-10-08 03:41

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0002_initial'),
        ('project', '0007_remove_project_unique_project_name_and_more'),
        ('tutorial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='project',
            name='unique_project_name',
            constraint=models.UniqueConstraint(models.F('project_type'), django.db.models.functions.text.Lower('topic'), django.db.models.functions.text.Lower('region'), models.F('project_number'), models.F('requesting_organization'), name='unique_project_name', violation_error_message='A project with the same type, topic, region, number and requesting organization already exists.'),
        ),
    ]
