# Generated by Django 5.1.6 on 2025-04-24 15:53

import apps.project.models
import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_processing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='aoi_geometry_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='processed_geometry_file',
        ),
        migrations.AlterField(
            model_name='project',
            name='group_size',
            field=models.PositiveSmallIntegerField(default=10, help_text='How big should a mapping session be? Group size refers to the number of tasks per mapping session.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_tasks_per_user',
            field=models.PositiveSmallIntegerField(blank=True, default=10, help_text='How many tasks each user is allowed to work on for this project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type_specifics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='verification_number',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many people do you want to see every tile before you consider it finished?'),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', django_choices_field.fields.IntegerChoicesField(choices=[(100, 'Input'), (200, 'Output'), (300, 'Stats')], choices_enum=apps.project.models.ProjectAssetTypeEnum)),
                ('mimetype', django_choices_field.fields.IntegerChoicesField(choices=[(100, 'application/geo+json'), (201, 'image/jpeg'), (202, 'image/png'), (203, 'image/gif')], choices_enum=apps.project.models.ProjectAssetMimetypeEnum)),
                ('file', models.FileField(help_text='The file associated with the asset', upload_to=apps.project.models.UploadHelper.project_asset)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_specific_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.projectasset'),
        ),
    ]
