# Generated by Django 5.1.6 on 2025-07-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_organization_abbreviation_organization_archived_at_and_more'),
        ('project', '0007_projecttask_legacy_task_id_and_more'),
    ]

    operations = [
    ]
