# Generated by Django 5.1.6 on 2025-07-19 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0005_alter_contributoruser_team'),
        ('project', '0007_organization_abbreviation_organization_archived_at_and_more'),
        ('tutorial', '0005_tutorial_old_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('topic', 'region', 'project_number', 'requesting_organization'), name='unique_project_name'),
        ),
    ]
