# Generated by Django 5.2.5 on 2025-10-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_slack_progress_notifications'),
        ('project', '0008_alter_project_unique_project_name'),
    ]

    operations = [
    ]
