# Generated by Django 5.1.6 on 2025-07-15 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_organization_abbreviation_project_archived_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_archived',
        ),
    ]
