# Generated by Django 5.1.6 on 2025-07-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_options_rename_name_project_topic_and_more'),
        ('project', '0009_organization_firebase_last_pushed_and_more'),
    ]

    operations = [
    ]
