# Generated by Django 5.1.6 on 2025-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If this flag is enabled, this project asset will be deleted in the future'),
        ),
    ]
