# Generated by Django 5.2.5 on 2025-10-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_merge_20251008_1121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttask',
            unique_together=set(),
        ),
    ]
