# Generated by Django 5.2.4 on 2025-07-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_merge_20250728_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='file_size',
            field=models.PositiveIntegerField(default=1, help_text='The size of the file in bytes'),
            preserve_default=False,
        ),
    ]
