# Generated by Django 5.1.6 on 2025-05-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_projectasset_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectasset',
            old_name='is_deleted',
            new_name='marked_as_deleted',
        ),
    ]
