# Generated by Django 5.2.5 on 2025-11-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projecttask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='firebase_id',
            field=models.CharField(max_length=36),
        ),
    ]
