# Generated by Django 5.2.5 on 2026-01-30 10:17

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projecttask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Find Features'), (2, 'Validate Footprints'), (10, 'Assess Images'), (3, 'Compare Dates'), (4, 'Check Completeness'), (7, 'View Streets'), (9, 'Locate Features')]),
        ),
    ]
