# Generated by Django 5.2.5 on 2026-02-17 12:03

import ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_projecttask_firebase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='firebase_id',
            field=models.CharField(default=ulid.ULID, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='firebase_id',
            field=models.CharField(default=ulid.ULID, max_length=36, unique=True),
        ),
    ]
