# Generated by Django 5.2.5 on 2026-06-08 15:00

from django.db import migrations


def backfill_project_geometry_data(apps, schema_editor):
    Project = apps.get_model("project", "Project")

    qs = (
        Project.objects.filter(aoi_geometry__isnull=False)
        .select_related("aoi_geometry",)
        .only("id", "aoi_geometry_id",)
    )

    for project in qs.iterator():
        aoi_geometry = project.aoi_geometry
        if not aoi_geometry:
            continue

        Project.objects.filter(id=project.id).update(
            centroid=aoi_geometry.centroid,
            bbox=aoi_geometry.bbox,
            total_area=aoi_geometry.total_area,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_alter_project_project_type"),
    ]

    operations = [
        migrations.RunPython(
            backfill_project_geometry_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
