# Generated by Django 5.1.6 on 2025-05-12 11:02

import django.contrib.gis.db.models.fields
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_is_deleted_projectasset_marked_as_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectasset',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
