# Generated by Django 5.1.6 on 2025-07-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_canonical_id'),
        ('project', '0011_projectasset_file_size'),
    ]

    operations = [
    ]
