# Generated by Django 5.2.4 on 2025-07-30 12:49

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_canonical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='old_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when project was pushed to firebase', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='canonical_id',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('old_id'), django.db.models.functions.comparison.Cast(models.F('id'), models.CharField())), output_field=models.CharField(), unique=True),
        ),
    ]
