# Generated by Django 5.2.5 on 2026-06-08 15:00

from django.db import migrations
from django.db.models import F


def backfill_project_geometry_data(apps, schema_editor):
    Project = apps.get_model("project", "Project")

    projects = []

    for project in (
        Project._default_manager
        .filter(aoi_geometry__isnull=False)
        .select_related("aoi_geometry")
        .iterator()
    ):
        project.centroid = project.aoi_geometry.centroid
        project.bbox = project.aoi_geometry.bbox
        project.total_area = project.aoi_geometry.total_area
        projects.append(project)

    Project._default_manager.bulk_update(
        projects,
        ["centroid", "bbox", "total_area"],
    )

class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_alter_project_project_type"),
    ]

    operations = [
        migrations.RunPython(
            backfill_project_geometry_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
