# Generated by Django 5.2.4 on 2025-07-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_merge_20250730_1323'),
        ('project', '0012_organization_old_id_and_more'),
    ]

    operations = [
    ]
