# Generated by Django 5.2.5 on 2026-04-28 14:28

from django.db import migrations

def backfill_image_provider(apps, schema_editor):
    Project = apps.get_model('project', 'Project')

    for project in Project._default_manager.all():
        if project.project_type != 7:  # STREET type
            continue

        if project.project_type_specifics is None:
            project.project_type_specifics = {}

        if 'imageProvider' not in project.project_type_specifics:
            project.project_type_specifics['imageProvider'] = {
                'name': 'MAPILLARY'
            }
        project.save(update_fields=['project_type_specifics'])

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_organization_firebase_id_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_image_provider, reverse_backfill),
    ]
