# Generated by Django 5.2.5 on 2026-04-28 14:28

import logging

from django.db import migrations

logger = logging.getLogger(__name__)

def backfill_image_provider(apps, schema_editor):
    Project = apps.get_model('project', 'Project')

    to_update = []
    for project in Project._default_manager.filter(project_type=7):  # STREET type
        if project.project_type_specifics is None:
            project.project_type_specifics = {}

        if 'image_provider' not in project.project_type_specifics:
            project.project_type_specifics['image_provider'] = {
                'name': 'mapillary'
            }
            to_update.append(project)

    updated_count = Project._default_manager.bulk_update(to_update, ['project_type_specifics'])
    logger.info(f"Field migration completed: {updated_count} projects backfilled image_provider")

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_organization_firebase_id_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_image_provider, reverse_backfill),
    ]
