# Generated by Django 5.2.5 on 2026-04-28 14:59

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_is_pano_to_pano_only(apps, schema_editor):
    """
    Migrate is_pano field to pano_only in mapillary_image_filters
    for all STREET-type projects to conform with updated schema.
    """
    Project = apps.get_model('project', 'Project')

    migrated_count = 0

    for project in Project._default_manager.all():
        if project.project_type != 7:  # STREET type
            continue

        if project.project_type_specifics is None:
            continue

        if 'mapillary_image_filters' in project.project_type_specifics:
            filters = project.project_type_specifics['mapillary_image_filters']
            if isinstance(filters, dict) and 'is_pano' in filters:
                logger.info(
                    f"Migrating is_pano to pano_only for project {project.id} ({project.name})"
                )
                filters['pano_only'] = filters.pop('is_pano')
                project.save(update_fields=['project_type_specifics'])
                migrated_count += 1

    logger.info(f"Field migration completed: {migrated_count} projects migrated is_pano to pano_only")


def reverse_pano_migration(apps, schema_editor):
    """
    Revert pano_only back to is_pano for compatibility.
    """
    Project = apps.get_model('project', 'Project')

    reverted_count = 0

    for project in Project._default_manager.all():
        if project.project_type != 7:  # STREET type
            continue

        if project.project_type_specifics is None:
            continue

        if 'mapillary_image_filters' in project.project_type_specifics:
            filters = project.project_type_specifics['mapillary_image_filters']
            if isinstance(filters, dict) and 'pano_only' in filters:
                logger.info(
                    f"Reverting pano_only to is_pano for project {project.id} ({project.name})"
                )
                filters['is_pano'] = filters.pop('pano_only')
                project.save(update_fields=['project_type_specifics'])
                reverted_count += 1

    logger.info(f"Reverse migration completed: {reverted_count} projects reverted pano_only to is_pano")


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_backfill_image_provider_for_street_projects'),
    ]

    operations = [
        migrations.RunPython(migrate_is_pano_to_pano_only, reverse_pano_migration),
    ]
