# Generated by Django 5.2.5 on 2026-06-17 05:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0002_initial'),
        ('project', '0013_migrate_aoi_geometry'),
        ('tutorial', '0003_tutorialtask_task_partition_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_name',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(models.F('project_type'), django.db.models.functions.text.Lower('topic'), django.db.models.functions.text.Lower('region'), models.F('project_number'), models.F('requesting_organization'), condition=models.Q(('status__in', [80, 70]), _negated=True), name='unique_project_name', violation_error_message='A project with the same type, topic, region, number and requesting organization already exists.'),
        ),
    ]
