# Generated by Django 5.2.5 on 2026-04-28 14:59

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_is_pano_to_pano_only(apps, schema_editor):
    """
    Migrate isPano field to panoOnly in mapillaryImageFilters
    for all STREET-type projects to conform with updated schema.
    """
    Project = apps.get_model('project', 'Project')
    
    migrated_count = 0
    
    for project in Project._default_manager.all():
        if project.project_type != 7:  # STREET type
            continue
        
        if project.project_type_specifics is None:
            continue
        
        if 'mapillaryImageFilters' in project.project_type_specifics:
            filters = project.project_type_specifics['mapillaryImageFilters']
            if isinstance(filters, dict) and 'isPano' in filters:
                logger.info(
                    f"Migrating isPano to panoOnly for project {project.id} ({project.name})"
                )
                filters['panoOnly'] = filters.pop('isPano')
                project.save(update_fields=['project_type_specifics'])
                migrated_count += 1
    
    logger.info(f"Field migration completed: {migrated_count} projects migrated isPano to panoOnly")


def reverse_pano_migration(apps, schema_editor):
    """
    Revert panoOnly back to isPano for compatibility.
    """
    Project = apps.get_model('project', 'Project')
    
    reverted_count = 0

    for project in Project._default_manager.all():
        if project.project_type != 7:  # STREET type
            continue
        
        if project.project_type_specifics is None:
            continue
        
        if 'mapillaryImageFilters' in project.project_type_specifics:
            filters = project.project_type_specifics['mapillaryImageFilters']
            if isinstance(filters, dict) and 'panoOnly' in filters:
                logger.info(
                    f"Reverting panoOnly to isPano for project {project.id} ({project.name})"
                )
                filters['isPano'] = filters.pop('panoOnly')
                project.save(update_fields=['project_type_specifics'])
                reverted_count += 1
    
    logger.info(f"Reverse migration completed: {reverted_count} projects reverted panoOnly to isPano")


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_backfill_image_provider_for_street_projects'),
    ]

    operations = [
        migrations.RunPython(migrate_is_pano_to_pano_only, reverse_pano_migration),
    ]
