# Generated by Django 5.1.6 on 2025-08-01 06:05

import apps.common.models
import django.db.models.manager
import django_choices_field.fields
from django.db import migrations, models
from ulid import ULID


def set_firebase_id_for_project(apps, schema_editor):
    Model = apps.get_model('project', 'Project')
    for obj in Model.cte_objects.all():
        obj.firebase_id = str(ULID())
        obj.save(update_fields=['firebase_id'])

def set_firebase_id_for_organization(apps, schema_editor):
    Model = apps.get_model('project', 'Organization')
    for obj in Model.cte_objects.all():
        obj.firebase_id = str(ULID())
        obj.save(update_fields=['firebase_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_merge_20250731_0850'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projecttask',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projecttaskgroup',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='canonical_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='canonical_id',
        ),
        migrations.RenameField(
            model_name='projecttask',
            old_name='legacy_task_id',
            new_name='firebase_id',
        ),
        migrations.RenameField(
            model_name='projecttaskgroup',
            old_name='legacy_group_id',
            new_name='firebase_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='firebase_push_status',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], choices_enum=apps.common.models.FirebasePushStatusEnum, null=True),
        ),
        migrations.AlterField(
            model_name='projecttaskgroup',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projecttaskgroup',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True),
        ),
        migrations.AddField(
            model_name='projecttaskgroup',
            name='firebase_push_status',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], choices_enum=apps.common.models.FirebasePushStatusEnum, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='firebase_last_pushed',
            field=models.DateTimeField(blank=True, help_text='The latest time when resource was pushed to firebase', null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='old_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projecttaskgroup',
            name='old_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.RunPython(set_firebase_id_for_project, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_firebase_id_for_organization, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='firebase_id',
            field=models.CharField(default=ULID, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='firebase_id',
            field=models.CharField(default=ULID, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttaskgroup',
            name='firebase_id',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projecttask',
            unique_together={('task_group', 'firebase_id')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttaskgroup',
            unique_together={('project', 'firebase_id')},
        ),
    ]
