# Generated by Django 5.2.5 on 2026-09-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_migrate_pano_only_for_street_projects'),
        ('project', '0014_remove_project_unique_project_name_and_more'),
    ]

    operations = [
    ]
