# Generated by Django 5.2.5 on 2026-09-01 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_project_unique_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aoi_geometry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.geometry'),
        ),
    ]
