# Generated by Django 5.2.4 on 2025-08-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_projectasset_stats_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectasset',
            old_name='stats_type',
            new_name='export_type',
        ),
    ]
