# Generated by Django 5.2.4 on 2025-08-12 09:02
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_rename_stats_type_projectasset_export_type'),
    ]

    operations = [
        UnaccentExtension(),
    ]
