# Generated by Django 5.2.5 on 2025-08-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_rename_stats_type_projectasset_export_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttaskgroup',
            name='number_of_groups',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
