# Generated by Django 5.2.4 on 2025-08-08 04:42

import apps.project.models
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_rename_stats_type_projectasset_export_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='asset_type_specifics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projectasset',
            name='external_url',
            field=models.CharField(blank=True, help_text='Provide link to the file associated with the asset', null=True),
        ),
        migrations.AddField(
            model_name='projectasset',
            name='input_type',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'AOI Geometry'), (200, 'Image with object annotations')], choices_enum=apps.project.models.ProjectAssetInputTypeEnum, null=True),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=models.FileField(blank=True, help_text='The file associated with the asset', null=True, upload_to=apps.project.models.UploadHelper.project_asset),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='marked_as_deleted',
            field=models.BooleanField(default=False, help_text='If this flag is enabled, this asset will be deleted in the future'),
        ),
    ]
