# Generated by Django 5.2.4 on 2025-08-20 14:38

import apps.project.models
import django.core.files.storage
import main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_projectasset_asset_type_specifics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=main.fields.OverwritableFileField(blank=True, help_text='The file associated with the asset', null=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=apps.project.models.UploadHelper.project_asset),
        ),
    ]
