# Generated by Django 5.2.4 on 2025-08-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20250812_0902'),
        ('project', '0019_alter_projectasset_mimetype'),
    ]

    operations = [
    ]
