# Generated by Django 5.2.5 on 2025-08-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_projecttaskgroup_number_of_groups'),
        ('project', '0019_alter_projectasset_mimetype'),
    ]

    operations = [
    ]
