# Generated by Django 5.2.4 on 2025-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_merge_20250822_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_instruction',
            field=models.TextField(blank=True, help_text='Provide project instruction', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='look_for',
            field=models.CharField(blank=True, help_text='What should the users look for (e.g. buildings, cars, trees)', max_length=255, null=True),
        ),
    ]
