# Generated by Django 5.2.5 on 2025-08-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_merge_20250822_0421'),
        ('project', '0020_merge_20250822_0627'),
    ]

    operations = [
    ]
