# Generated by Django 5.2.5 on 2025-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_merge_20250822_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_instruction',
            field=models.TextField(default='Unknown', help_text='Provide mission statement.'),
            preserve_default=False,
        ),
    ]
