# Generated by Django 5.2.4 on 2025-08-28 09:02

from django.db.models.functions import Concat
from django.db import migrations, models


def update_tasks(apps, schema_editor):
    ProjectTask = apps.get_model('project', 'ProjectTask')
    ProjectTask.cte_objects.annotate(
        generated_id=Concat(models.Value("legacy_"), models.F("id")),
    ).update(firebase_id=models.F("generated_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_merge_20250822_0421'),
    ]

    operations = [
        migrations.RunPython(update_tasks, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projecttask',
            name='firebase_id',
            field=models.CharField(max_length=30),
        ),
    ]
