# Generated by Django 5.2.4 on 2025-08-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_projecttask_firebase_id'),
        ('project', '0021_project_project_instruction_alter_project_look_for'),
    ]

    operations = [
    ]
