# Generated by Django 5.2.4 on 2025-09-01 13:35

import apps.project.models
import django.core.files.storage
import main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_merge_20250828_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=main.fields.OverwritableFileField(blank=True, help_text='The file associated with the asset', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=apps.project.models.UploadHelper.project_asset),
        ),
    ]
