# Generated by Django 5.2.4 on 2025-08-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_merge_20250828_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_thread_ts',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
