# Generated by Django 5.2.4 on 2025-09-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_projectasset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_thread_ts',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
