# Generated by Django 5.2.5 on 2025-09-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_projectasset_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_type_specific_output',
            new_name='project_type_specific_output_asset',
        ),
    ]
