# Generated by Django 5.2.5 on 2025-09-04 02:48

import django.db.models.deletion
from django.db import migrations, models
from utils.common import recursively_find_value


def set_aoi_asset(apps, schema_editor):
    Model = apps.get_model('project', 'Project')
    for obj in Model.cte_objects.all():
        aoi_id = recursively_find_value(obj.project_type_specifics, "aoi_geometry")
        if aoi_id:
            obj.aoi_geometry_input_asset = int(aoi_id)
            obj.save(update_fields=['aoi_geometry_input_asset'])


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_rename_project_type_specific_output_project_project_type_specific_output_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aoi_geometry_input_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.projectasset'),
        ),
        migrations.RunPython(set_aoi_asset, reverse_code=migrations.RunPython.noop),
    ]
