# Generated by Django 5.2.5 on 2025-09-04 18:14

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_project_aoi_geometry_input_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_contribution_date',
            field=models.DateField(blank=True, help_text='Last recent contribution date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_contributor_users',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who made contributions to this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_results',
            field=models.PositiveIntegerField(default=0, help_text='Number of results contributed to this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_results_for_progress',
            field=models.PositiveIntegerField(default=0, help_text='Number of results contributed to this project that can be used to calculate the progress of this project. Max no. of results per task that can be used to calculate progress is equal to the `verification number`'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentage of the required contribution that has been completed', validators=[utils.fields.validate_percentage]),
        ),
    ]
