# Generated by Django 5.2.5 on 2025-09-05 03:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_project_aoi_geometry_input_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='project',
            name='total_area',
            field=models.FloatField(default=None, null=True),
        ),
    ]
