# Generated by Django 5.2.5 on 2025-09-05 01:15

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_project_last_contribution_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_status',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'On going'), (2, 'Completed')], default=1),
        ),
    ]
