# Generated by Django 5.2.5 on 2025-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_project_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_thread_ts',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
