# Generated by Django 5.2.5 on 2025-09-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_project_bbox_project_total_area'),
        ('project', '0027_project_progress_status'),
    ]

    operations = [
    ]
