# Generated by Django 5.2.5 on 2025-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_merge_20250906_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_thread_ts',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
