# Generated by Django 5.2.5 on 2025-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_merge_20250906_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_message',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
