# Generated by Django 5.2.5 on 2025-09-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0012_contributorusergroupmembershiplogtemp'),
        ('project', '0030_geometry_project_aoi_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contributor.contributorteam'),
        ),
    ]
