apiVersion: v2
name: mapswipe-backend-helm
description: "Helm Chart to deploy the Mapswipe Backend (Alpha instances)"
type: application
version: 0.2.1-SET-BY-CICD  # managed by release.sh
sources:
  - https://github.com/mapswipe/mapswipe-backend/

dependencies:
  - name: toggle-django-helm
    alias: app
    version: 0.2.0
    repository: oci://ghcr.io/toggle-corp
