app:
  environment: PROD
  # Global Image
  appTypeEnvName: "APP_TYPE"
  image:
    name: SET-BY-CICD-IMAGE
    tag: SET-BY-CICD-TAG
    imagePullPolicy: IfNotPresent

  ingress:
    enabled: true
    className: nginx

  redis:
    enabled: true
    fullnameOverride: "mapswipe-redis"

  postgresql:
    enabled: true
    fullnameOverride: "mapswipe-postgres"
    auth:
      database: "mapswipe"
    primary:
      persistence:
        storageClass:
        size: "2Gi"

  minio:
    enabled: true
    fullnameOverride: mapswipe-minio
    global:
      defaultStorageClass:
    apiIngress:
      ingressClassName: nginx
    auth:
      rootUser: mapswipe
      rootPassword:
    persistence:
      size: "1Gi"
    defaultBuckets: static-data,media-data
    provisioning:
      extraCommands:
        - "mc anonymous set download provisioning/static-data"

  api:
    containerPort: 80
    command: ["misc/prod/run_web.sh"]
    resources:
      requests:
        cpu: "0.2"

  worker:
    enabled: true
    beat:
      command: ["celery", "-A", "main", "beat", "-l", "INFO"]
      resources:
        requests:
          cpu: "0.1"
          memory: 0.5Gi
        limits:
          cpu: "1"
          memory: 1Gi
    flower:
      enabled: false
    queueDefaultResources:
      requests:
        cpu: "0.1"
        memory: 1Gi
      limits:
        cpu: "4"
        memory: 2Gi
    queueCommandPrefix:
      - "celery"
      - "-A"
      - "main"
      - "worker"
      - "-l"
      - "INFO"
    queues:
      # NOTE: Make sure keys are lowercase
      default:
        enabled: true
        replicaCount: 1
        celeryArgs:
          - "-Q"
          - "default"
          - "--concurrency"
          - "4"
          - "--max-tasks-per-child"
          - "10"

  # NOTE: Check main/settings.py for all available options
  env:
    APP_RELEASE: "{{ $.Values.image.tag }}"
    APP_ENVIRONMENT: "{{ $.Values.environment }}"
    # AWS
    AWS_S3_ENABLED: "true"
    AWS_S3_ENDPOINT_URL: "https://{{ $.Values.minio.apiIngress.hostname }}/"
    AWS_S3_STATIC_BUCKET_NAME: "static-data"
    AWS_S3_MEDIA_BUCKET_NAME: "media-data"
    # App Domain
    SESSION_COOKIE_DOMAIN: "{{ required \".Values.env.SESSION_COOKIE_DOMAIN\" nil }}"
    CSRF_COOKIE_DOMAIN: "{{ required \".Values.env.CSRF_COOKIE_DOMAIN\" nil }}"

  # NOTE: Check main/settings.py for all available options
  secrets:
    SECRET_KEY: "{{ required \".Values.secrets.SECRET_KEY\" nil }}"
    # Postgres
    POSTGRES_DB: "{{ $.Values.postgresql.auth.database }}"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "{{ $.Values.postgresql.auth.postgresPassword }}"
    POSTGRES_HOST: "{{ include \"postgresql.v1.primary.fullname\" $.Subcharts.postgresql }}"
    POSTGRES_PORT: "{{ include \"postgresql.v1.service.port\" $.Subcharts.postgresql }}"
    # Minio (S3)
    AWS_S3_ACCESS_KEY_ID: "{{ required \".Values.minio.auth.rootUser\" $.Values.minio.auth.rootUser }}"
    AWS_S3_SECRET_ACCESS_KEY: "{{ required \".Values.minio.auth.rootPassword\" $.Values.minio.auth.rootPassword }}"
    AWS_S3_REGION_NAME: "us-east-1"
    # Redis
    CELERY_REDIS_URL: "redis://{{ printf \"%s-master\" (include \"common.names.fullname\" $.Subcharts.redis) }}:6379/0"
    CACHE_REDIS_URL: "redis://{{ printf \"%s-master\" (include \"common.names.fullname\" $.Subcharts.redis) }}:6379/1"
